### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']'  & Error building extension 'fused': [1/3] c++ -MMD -MF

### ISSUE THREAD

**Issue by kanak8278** [KellyYutongHe/satellite-pixel-synthesis-pytorch#4]
Hi, I am trying to train and replicate the model. While running train or text python files. I am facing the bellow error.

Traceback (most recent call last):
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_3dis.py", line 16, in <module>
    import model
  File "/export/home/kraj/satellite-pixel-synthesis-pytorch/model/__init__.py", line 1, in <module>
    from .Discriminators import *
  File "/export/home/kraj/satellite-pixel-synthesis-pytorch/model/Discriminators.py", line 9, in <module>
    from .blocks import ConvLayer, ResBlock, EqualLinear
  File "/export/home/kraj/satellite-pixel-synthesis-pytorch/model/blocks.py", line 8, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/export/home/kraj/satellite-pixel-synthesis-pytorch/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_act.py", line 10, in <module>
    fused = load(
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/TH -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /export/home/kraj/anaconda3/envs/spsp/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act.cpp -o fused_bias_act.o 
FAILED: fused_bias_act.o 
c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/TH -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /export/home/kraj/anaconda3/envs/spsp/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act.cpp -o fused_bias_act.o 
c++: error: unrecognized command line option ‘-std=c++17’
[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/TH -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /export/home/kraj/anaconda3/envs/spsp/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_60,code=sm_60 --compiler-options '-fPIC' -std=c++17 -c /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/TH -isystem /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /export/home/kraj/anaconda3/envs/spsp/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_60,code=sm_60 --compiler-options '-fPIC' -std=c++17 -c /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc warning : The -std=c++17 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3:0,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++14 or later compatible compiler is required to use ATen.
 #error C++14 or later compatible compiler is required to use ATen.
  ^
In file included from /usr/include/c++/4.8.2/mutex:35:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:4,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/Context.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:4:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/Context.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:138:20: error: missing binary operator before token "("
 #if __has_attribute(used)
                    ^
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:218:22: error: missing binary operator before token "("
 #elif __has_attribute(always_inline) || defined(__GNUC__)
                      ^
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/string_view.h:4:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/StringUtil.h:6,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:6,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/Context.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:16:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
 #error \
  ^
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
  ^
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/Exception.h:7:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/Context.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/variant.h:243:2: error: #error "MPark.Variant requires C++11 support."
 #error "MPark.Variant requires C++11 support."
  ^
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/typeid.h:25:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/core/ScalarTypeToTypeMeta.h:5,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/core/TensorOptions.h:10,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/core/TensorImpl.h:11,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/core/GeneratorImpl.h:8,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/Generator.h:22,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/Context.h:3,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/ATen.h:7,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/TypeIndex.h:81:2: error: #error "You're running a too old version of GCC. We need GCC 5 or later."
 #error "You're running a too old version of GCC. We need GCC 5 or later."
  ^
In file included from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:11:0,
                 from /export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:12,
                 from /export/home/kraj/satellite-pixel-synthesis-pytorch/op/fused_bias_act_kernel.cu:7:
/export/home/kraj/anaconda3/envs/spsp/lib/python3.8/site-packages/torch/include/c10/util/LeftRight.h:8:24: fatal error: shared_mutex: No such file or directory
 #include <shared_mutex>
                        ^
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by kanak8278** [comment]
This was a version error. The CUDA was not setup properly.
